# Generated by Django 4.0.3 on 2022-03-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_group_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='asd', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='surname',
            field=models.CharField(default='asd', max_length=15),
            preserve_default=False,
        ),
    ]
