# Generated by Django 4.0.3 on 2022-03-24 16:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_alter_customuser_name_alter_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=45)),
                ('short_name', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Система оцінювання')),
                ('numerical_form', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GroupSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_of_hours', models.PositiveIntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.group')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('topic', models.CharField(max_length=200, verbose_name='Тема')),
                ('homework', models.CharField(max_length=200, verbose_name='Домашнє завдання')),
                ('note', models.CharField(max_length=200, verbose_name='Примітка')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subgroup', models.CharField(max_length=10, verbose_name='Підгрупа')),
                ('semester', models.PositiveIntegerField(verbose_name='Семестр')),
                ('academic_year', models.CharField(max_length=4, verbose_name='Навчальний рік')),
                ('group_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.groupsubject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Назва предмету')),
                ('short_name', models.CharField(max_length=33, verbose_name='Скорочена назва предмету')),
                ('evaluation_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.evaluationsystem')),
            ],
        ),
        migrations.CreateModel(
            name='StudentGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.PositiveIntegerField()),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.attendance')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.student')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='teacher_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.teachersubject'),
        ),
        migrations.AddField(
            model_name='groupsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.subject'),
        ),
    ]
