# Generated by Django 4.0.3 on 2022-03-24 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_attendance_evaluationsystem_groupsubject_lesson_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
