# Generated by Django 4.0.3 on 2022-03-27 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_alter_group_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='journal.group'),
        ),
    ]
