# Generated by Django 4.0.3 on 2022-03-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0011_lessontype_lesson_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='about',
            field=models.TextField(null=True),
        ),
    ]
