# Generated by Django 4.0.3 on 2022-03-30 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0014_group_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(max_length=45, unique=True, verbose_name='URL'),
        ),
    ]
