# Generated by Django 4.0.3 on 2022-03-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0016_remove_message_sender_name_message_from_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='slug',
            field=models.SlugField(default='mathematic', max_length=45, unique=True, verbose_name='identificator'),
            preserve_default=False,
        ),
    ]
