# Generated by Django 4.0.3 on 2022-03-31 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0017_subject_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_check',
            field=models.BooleanField(default=False),
        ),
    ]
