# Generated by Django 4.0.3 on 2022-04-01 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0019_alter_message_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
