# Generated by Django 4.0.3 on 2022-04-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0021_lessontype_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='subgroup',
        ),
        migrations.RemoveField(
            model_name='teachersubject',
            name='subgroup',
        ),
        migrations.AddField(
            model_name='teachersubject',
            name='students',
            field=models.CharField(default=15, max_length=200),
            preserve_default=False,
        ),
    ]
