# Generated by Django 4.0.3 on 2022-04-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0022_remove_student_subgroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='last_update',
            field=models.DateField(auto_now=True),
        ),
    ]
