# Generated by Django 4.0.3 on 2022-04-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0023_lesson_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
