# Generated by Django 4.0.3 on 2022-04-04 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0024_alter_lesson_last_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentgrade',
            name='attendance',
        ),
    ]
