# Generated by Django 4.0.3 on 2022-04-04 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0025_remove_studentgrade_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=3)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.student')),
            ],
        ),
        migrations.DeleteModel(
            name='StudentGrade',
        ),
    ]
