# Generated by Django 4.0.3 on 2022-04-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0026_studentlesson_delete_studentgrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlesson',
            name='mark',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
