# Generated by Django 4.0.3 on 2022-04-07 09:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0027_alter_studentlesson_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlesson',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
