# Generated by Django 4.0.3 on 2022-04-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0029_alter_lesson_homework_alter_lesson_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='specializations',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
