# Generated by Django 4.0.3 on 2022-04-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0030_teacher_specializations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='specializations',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='teachersubject',
            name='students',
            field=models.TextField(null=True),
        ),
    ]
