# Generated by Django 4.0.3 on 2022-04-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0033_alter_teacher_specializations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='specializations',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='teachersubject',
            name='students',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
