# Generated by Django 4.0.3 on 2022-05-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0037_alter_attendance_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='specializations',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='Про себе'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='День народження'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(max_length=45, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='patronymic',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='По батькові'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='surname',
            field=models.CharField(max_length=45, verbose_name='Прізвище'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Примітка'),
        ),
    ]
