# Generated by Django 4.0.3 on 2022-05-16 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0038_remove_teacher_specializations_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['surname', 'name', 'patronymic']},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['user']},
        ),
        migrations.AlterModelOptions(
            name='studentlesson',
            options={'ordering': ['lesson__date']},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['user']},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
    ]
