# Generated by Django 4.0.3 on 2022-05-17 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0039_alter_customuser_options_alter_lesson_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='teachersubject',
            name='group_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.groupsubject', verbose_name='Предмет'),
        ),
    ]
