# Generated by Django 4.0.3 on 2022-05-19 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0041_student_study_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Назва')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.specialization')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.teacher')),
            ],
        ),
    ]
