# Generated by Django 4.0.3 on 2022-05-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0042_specialization_teacherspecialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlesson',
            name='read_only',
            field=models.BooleanField(default=False),
        ),
    ]
