# Generated by Django 4.0.3 on 2022-06-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0043_studentlesson_read_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlesson',
            name='mark',
            field=models.CharField(max_length=5, null=True, verbose_name='Оцінка'),
        ),
    ]
