# Generated by Django 4.0.3 on 2022-06-06 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0044_alter_studentlesson_mark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Назва')),
            ],
            options={
                'verbose_name': 'Роль у системі',
                'verbose_name_plural': 'Ролі у системі',
            },
        ),
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name': 'Відвідуваність', 'verbose_name_plural': 'Відвідуваність'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['surname', 'name', 'patronymic'], 'verbose_name': 'Користувач', 'verbose_name_plural': 'Користувачі'},
        ),
        migrations.AlterModelOptions(
            name='evaluationsystem',
            options={'verbose_name': 'Система оцінювання', 'verbose_name_plural': 'Системи оцінювання'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Група', 'verbose_name_plural': 'Групи'},
        ),
        migrations.AlterModelOptions(
            name='groupsubject',
            options={'verbose_name': 'Предмет групи', 'verbose_name_plural': 'Предмети груп'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['date'], 'verbose_name': 'Пара', 'verbose_name_plural': 'Пари'},
        ),
        migrations.AlterModelOptions(
            name='lessontype',
            options={'verbose_name': 'Тип пари', 'verbose_name_plural': 'Типи пар'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Повідомлення', 'verbose_name_plural': 'Повідомлення'},
        ),
        migrations.AlterModelOptions(
            name='replacement',
            options={'verbose_name': 'Заміна', 'verbose_name_plural': 'Заміни'},
        ),
        migrations.AlterModelOptions(
            name='specialization',
            options={'verbose_name': 'Сцеціалізація', 'verbose_name_plural': 'Спеціалізації'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['user'], 'verbose_name': 'Студент', 'verbose_name_plural': 'Студенти'},
        ),
        migrations.AlterModelOptions(
            name='studentlesson',
            options={'ordering': ['lesson__date'], 'verbose_name': 'Пара студента', 'verbose_name_plural': 'Пари студентів'},
        ),
        migrations.AlterModelOptions(
            name='studyform',
            options={'verbose_name': 'Форма навчання', 'verbose_name_plural': 'Форми навчання'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Предмет', 'verbose_name_plural': 'Предмети'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['user'], 'verbose_name': 'Викладач', 'verbose_name_plural': 'Викладачі'},
        ),
        migrations.AlterModelOptions(
            name='teacherspecialization',
            options={'verbose_name': 'Спеціалізація викладача', 'verbose_name_plural': 'Спеціалізації викладачів'},
        ),
        migrations.AlterModelOptions(
            name='teachersubject',
            options={'verbose_name': 'Предмет викладача', 'verbose_name_plural': 'Предмети викладачів'},
        ),
        migrations.AlterField(
            model_name='evaluationsystem',
            name='name',
            field=models.CharField(max_length=45, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач'),
        ),
    ]
