# Generated by Django 4.0.3 on 2022-06-06 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0045_role_alter_attendance_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='roles',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='journal.role', verbose_name='Роль у системі'),
            preserve_default=False,
        ),
    ]
