# Generated by Django 4.0.3 on 2022-06-06 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0047_remove_customuser_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='roles',
            new_name='role',
        ),
    ]
